### ISSUE TITLE
odoo-gdpr to OCA?

### ISSUE THREAD

**Issue by rafaelbn** [vertelab/odoo-gdpr#1]
Dear @robch2342 @anderswallenquist @HaojunZou ,

Nice to meet you

- It looks like this repo is the only one world-wide about GDPR :thinking: 
- It lools like a great job here :+1: 

- Do you plan to migrate them to a new version like Odoo v10 or v11?
- Could you accept if other company migrate them to a new version under https://github.com/oca umbrella?
- Do you know OCA https://odoo-community.org/ ?

Thanks in advance for any info

Regards,
Rafael

**Comment by anderswallenquist** [comment]
Hello @rafaelbn, thanks for your interest in our GDPR-module.

* Do you plan to migrate them to a new version like Odoo v10 or v11?

The module (and most of our modules are result of customer projects), so this module will expand with more functionality and more plattforms as the module get contributions from our customers or others. We are in dialog with customers about both v10 and v11, but does not have a given timetable for it. I think v10 is on top (we don't have much customers on 11 yet). 

So yes, if you or any other company wan't to contribute you are welcome. You can contribute with code or pay our programmers to to contributions.

Yes we are aware or OCA (we have done contributions in code and are member). OCA does much good for Odoo and are first stop when we are looking for new modules. I'm not (yet) convinced that its for the best for the module to move it under OCA umbrella. Under OCA umbrella; who is in charge for project lead and functional/technical decisions?  For examples we have contributed with our project-scrum for the OCA project-agile but we does know how this lands yet.

Regards,
Anders Wallenquist

**Comment by rafaelbn** [comment]
Hello @anderswallenquist ,

Maybe you could participate in next meeting OCA GDPR conference call: Friday 6th 13:00 CET: https://odoo-community.org/groups/gdpr-61/gdpr-74059?mode=thread&date_begin=&date_end=

> Under OCA umbrella; who is in charge for project lead and functional/technical decisions? For examples we have contributed with our project-scrum for the OCA project-agile but we does know how this lands yet

The project lead is the Team Leader and the PSC of each project. I usually go to https://odoo-community.org/page/List but is not up-to-date so really you have done a good question! :thinking: 

Could you point me to your contribution of "project-scrum" please? Thanks! :smile:  Is this one? https://github.com/OCA/project-agile/pull/1

Thanks
Regards,
Rafael

**Comment by rafaelbn** [comment]
Hi @anderswallenquist ,

Here you are https://github.com/orgs/OCA/teams/ this are all the people who are in charge of projects and functional/technical decision

In the case of project is https://github.com/orgs/OCA/teams/?utf8=%E2%9C%93&query=project

:+1:

**Comment by rafaelbn** [comment]
Hello @anderswallenquist ,

We finally did an approach in OCA, maybe you would like to take a look.

- https://github.com/OCA/data-protection

- https://github.com/OCA/data-protection/tree/10.0/privacy 
- https://github.com/OCA/data-protection/tree/10.0/privacy_consent 

Regards! :smile: :+1:
